version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "events-db"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  node:
    image: "node:lts-jessie-slim"
    depends_on:
      - db
